# Generated by Django 5.1 on 2025-10-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cine', models.CharField(help_text='Nombre del cine', max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('numero_salas', models.IntegerField()),
                ('imagen_sucursal', models.ImageField(blank=True, null=True, upload_to='img_sucursales/')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sala', models.IntegerField()),
                ('tipo_sala', models.CharField(choices=[('VIP', 'VIP'), ('Tradicional', 'Tradicional'), ('4DX', '4DX'), ('3D', '3D'), ('Junior', 'Junior'), ('IMAX', 'IMAX')], max_length=20)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Ocupada', 'Ocupada'), ('Desocupada', 'Desocupada'), ('En mantenimiento', 'En mantenimiento')], max_length=20)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app_sucural_sala.sucursal')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
